### ISSUE TITLE
Can't compile on MacOS 15

### ISSUE THREAD

**Issue by aminta** [arcanebyte/lisaem#11]
```
../src/osx/carbon/dcscreen.cpp:73:13: error: 'CGDisplayCreateImage' is unavailable: obsoleted in macOS 15.0 - Please use ScreenCaptureKit instead.
   73 |     image = CGDisplayCreateImage(kCGDirectMainDisplay);
      |             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:383:33: note: 'CGDisplayCreateImage' has been explicitly marked unavailable here
  383 | CG_EXTERN CGImageRef __nullable CGDisplayCreateImage(CGDirectDisplayID displayID)
      |                                 ^
1 error generated.
make: *** [monolib_carbon_dcscreen.o] Error 1
make: *** Waiting for unfinished jobs....
```
Trying launching `build-wx3.2.1-modern-macosx.sh` or `build-wx3.2.3-modern-macosx.sh` or `build-wx3.2.4-modern-macosx.sh` or `build-wx3.2.5-modern-macosx.sh` on my MacMini M1 2020 MacOS 15.1.1 / Xcode 16.1.

Launching `build-wx3.1.5-modern-macosx.sh` returns `configure: error: building C++ programs doesn't work, try using --with-macosx-version-min with a different OS version or omitting it entirely.`

**Comment by arcanebyte** [comment]
Thanks for the report. I will take a look at this on an M1 Pro w/ 15.1.1 and get back to you.

**Comment by busterswt** [comment]
Turns out this is an issue with wxWidgets, as macOS has deprecated that call in favor of another library. To workaround this, I have pinned the minimum version of macOS to 14.5 for the latest build using wxWidgets 3.2.6 (to be published soon). Let me know how this works for you.
